[project]
name = "pyllmvalidate-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.82.1",
    "pydantic>=2.11.5",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
